### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by mansisindhu** [vivek13420/alluring-bottle-5827#25]
- Website is not properly responsive - ✓
- Input box not working - ✓
- There is already an item hardcoded in cart, user didn’t add it -✓
- There are many routes and links not working - ✓
- After successful login response still login and signup button is showing - ✓
- Password is not masked - ✓      
- Can’t reset the filters - ✓
- Can’t add any product to wishlist -✓
- Can’t add any product to cart and can’t checkout-✓
- Functionality and logic is lacking - ✓
- Unnecessary consoles - ✓

**Comment by Devendra0192** [comment]
improved overall functionalities of the project  #31
